### ISSUE TITLE
sha数据维度对不上

### ISSUE THREAD

**Issue by woshizhangcheng** [gjy3035/C-3-Framework#105]
```
loss.py:431: UserWarning: Using a target size (torch.Size([690, 1024])) that is different to the input size (torch.Size([696, 1024])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size

File "train.py", line 63, in <module>
    cc_trainer.forward()
  File "/data/share/imageAlgorithm/zhangcheng/code/C-3-Framework/trainer.py", line 65, in forward
    self.train()
  File "/data/share/imageAlgorithm/zhangcheng/code/C-3-Framework/trainer.py", line 94, in train
    pred_map = self.net(img, gt_map)
  File "/home/zhangcheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/data/share/imageAlgorithm/zhangcheng/code/C-3-Framework/models/CC.py", line 40, in forward
    self.loss_mse= self.build_loss(density_map.squeeze(), gt_map.squeeze())
  File "/data/share/imageAlgorithm/zhangcheng/code/C-3-Framework/models/CC.py", line 45, in build_loss
    loss_mse = self.loss_mse_fn(density_map, gt_data)
  File "/home/zhangcheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/zhangcheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 431, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/zhangcheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py", line 2203, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/zhangcheng/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/functional.py", line 52, in broadcast_tensors
    return torch._C._VariableFunctions.broadcast_tensors(tensors)
RuntimeError: The size of tensor a (680) must match the size of tensor b (674) at non-singleton dimension 0


```
我检查了一遍啥数据集中的图片和对应csv的维度都是对的上，但是训练一起来就会提示我维度对不上

**Comment by feixuedudiao** [comment]
我也遇到这样的问题，需要对test部分数据做Padding，保持crop_image和crop_den在每次验证时stack到一起。

**Comment by liuliu96** [comment]
> 我也遇到这样的问题，需要对test部分数据做Padding，保持crop_image和crop_den在每次验证时stack到一起。

请问大佬在哪做padding呀

**Comment by BoltenWang-Meta** [comment]
是因为MCNN最后的4倍上采样，如果输入图像尺寸不是4的倍数的话gt和pred尺寸不一样，可以这样更改：
def get_min_size(self, batch):
        min_ht = 1e5
        min_wd = 1e5
        for i_sample in batch:
            _, ht, wd = i_sample.shape
            if ht < min_ht:
                min_ht = ht
            if wd < min_wd:
                min_wd = wd
        if min_ht % 4 != 0:
            min_ht = (min_ht // 4) * 4
        if min_wd % 4 != 0:
            min_wd = (min_wd // 4) * 4
        return min_ht, min_wd

**Comment by d888999** [comment]
UserWarning: Using a target size (torch.Size([1, 768, 1024])) that is different to the input size (torch.Size([1, 1, 768, 1024])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/c404/data1/zhangjiaxing/.conda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/loss.py:431: UserWarning: Using a target size (torch.Size([1, 683, 1024])) that is different to the input size (torch.Size([1, 1, 680, 1024])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
Traceback (most recent call last):
  File "/home/c404/data1/zhangjiaxing/Framework/C-3-Framework/train.py", line 60, in <module>
    cc_trainer.forward()
  File "/home/c404/data1/zhangjiaxing/Framework/C-3-Framework/trainer.py", line 64, in forward
    self.train()
  File "/home/c404/data1/zhangjiaxing/Framework/C-3-Framework/trainer.py", line 91, in train
    pred_map = self.net(img, gt_map)
  File "/home/c404/data1/zhangjiaxing/.conda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/c404/data1/zhangjiaxing/Framework/C-3-Framework/models/CC.py", line 44, in forward
    self.loss_mse = self.build_loss(density_map, gt_map)
  File "/home/c404/data1/zhangjiaxing/Framework/C-3-Framework/models/CC.py", line 49, in build_loss
    loss_mse = self.loss_mse_fn(density_map, gt_data)
  File "/home/c404/data1/zhangjiaxing/.conda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/c404/data1/zhangjiaxing/.conda/envs/py37/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 431, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/home/c404/data1/zhangjiaxing/.conda/envs/py37/lib/python3.7/site-packages/torch/nn/functional.py", line 2203, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/home/c404/data1/zhangjiaxing/.conda/envs/py37/lib/python3.7/site-packages/torch/functional.py", line 52, in broadcast_tensors
    return torch._C._VariableFunctions.broadcast_tensors(tensors)
RuntimeError: The size of tensor a (680) must match the size of tensor b (683) at non-singleton dimension 2
试了试还是不行
