### ISSUE TITLE
test.py error

### ISSUE THREAD

**Issue by Byronnar** [gjy3035/C-3-Framework#63]
the model: 11-ResSFCN-101_all_ep_94_mae_26.8_mse_66.1.pth

Traceback (most recent call last):
  File "test.py", line 151, in <module>
    main()
  File "test.py", line 50, in main
    test(file_list[0], model_path)
  File "test.py", line 56, in test
    net.load_state_dict(torch.load(model_path))
  File "/home/byronnar/anaconda3/envs/dev/lib/python3.6/site-packages/torch/nn/modules/module.py", line 845, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CrowdCounter:
请问这个模型是不能不能使用么？

**Comment by lizxko2009** [comment]
Traceback (most recent call last):
  File "test.py", line 153, in <module>
    main()
  File "test.py", line 50, in main
    test(file_list[0], model_path)
IndexError: list index out of range
请问一下这个错误您是怎么解决的？谢谢

**Comment by gjy3035** [comment]
@lizxko2009 file list有问题，建议使用b进行调试。

**Comment by FCgogogo** [comment]
> Traceback (most recent call last): File "test.py", line 153, in main() File "test.py", line 50, in main test(file_list[0], model_path) IndexError: list index out of range 请问一下这个错误您是怎么解决的？谢谢

我也遇到了这个问题，请问你解决了吗
