### ISSUE TITLE
How to train on Shanghai tech part A

### ISSUE THREAD

**Issue by Siddartha123** [gjy3035/C-3-Framework#79]
Hi, Thank you for the code and appreciate for the work. I am able to download the QNRF and SHB datasets from the links you have provided and able to train and test, awesome :)  But when I do the same with Shanghai tech part A (SHA), I am unable to proceed with training with input and output tensor mismatch. I will share the logs if required, but are there any extra steps required for training of Shanghai tech Part A. I have downloaded training data from the dataset provided in the link (Onedrive link).
It would be of great help, if you suggest any steps.

**Comment by MagazzuGaetano** [comment]
i think i have your same problem:

Traceback (most recent call last):
  File "train.py", line 63, in <module>
    cc_trainer.forward()
  File "/content/drive/My Drive/C-3-Framework/trainer.py", line 65, in forward
    self.train()
  File "/content/drive/My Drive/C-3-Framework/trainer.py", line 93, in train
    pred_map = self.net(img, gt_map)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/content/drive/My Drive/C-3-Framework/models/CC.py", line 40, in forward
    self.loss_mse= self.build_loss(density_map.squeeze(), gt_map.squeeze())               
  File "/content/drive/My Drive/C-3-Framework/models/CC.py", line 44, in build_loss
    loss_mse = self.loss_mse_fn(density_map, gt_data)  
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/loss.py", line 432, in forward
    return F.mse_loss(input, target, reduction=self.reduction)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py", line 2542, in mse_loss
    expanded_input, expanded_target = torch.broadcast_tensors(input, target)
  File "/usr/local/lib/python3.6/dist-packages/torch/functional.py", line 62, in broadcast_tensors
    return _VF.broadcast_tensors(tensors)
RuntimeError: The size of tensor a (408) must match the size of tensor b (404) at non-singleton dimension 1

**Comment by MagazzuGaetano** [comment]
I think I had your same problem,
I solved it by preprocessing SHHA, as recommended by the author
in another issue "Dimension Error! SHHA!"

code:
[preprocessing_SHHA.txt](https://github.com/gjy3035/C-3-Framework/files/4808447/preprocessing_SHHA.txt)

**Comment by 13970716471** [comment]
未定义函数或变量 'get_density_map_gaussian'。

出错 Untitled (line 38)
    im_density = get_density_map_gaussian(im,annPoints,15,4);
 Hello,please tell me why.

**Comment by 13970716471** [comment]
> I directly use the SHHA dataset file in csv format provided by the author and still report an error
